"""test_rehunt.py — regression + dry-run for the DR4 rehunt harness.

Runs fully offline. The headline test is a *closed-loop regression*: feed the
committed DR3 v2 roster's own input columns back through the harness (adapter ->
rehunt -> derive_row_v2) and assert it reproduces today's tier roster exactly.
That pins the harness as a faithful wrapper of the production cascade
(``scripts/streaming/v2_corrected/consumer_v2.py``) — if anyone forks/reimplements
the science here, this test breaks.

Run::

    ~/claude_projects/ostinato/.venv/bin/python -m pytest \
        scripts/dr4_pipeline/rehunt/test_rehunt.py -q

or as a plain script (``python test_rehunt.py``) for a one-shot dry-run summary.

KEY FINDING baked into these tests (see also the module docstring of diff.py and
the RESEARCH_LOG block returned by the build task):

  * The committed ``data/derived/main_hunt_derived_v2.parquet`` was generated by
    an EARLIER code path that fixed M_1 = 1.5 (its ``M1_msun_v2`` column is
    uniformly 1.5) — it PRE-DATES the current ``consumer_v2.select_m1`` FLAME
    preference. So a faithful re-run reproduces it ONLY when M_1 is forced to the
    same fixed 1.5 (no FLAME leak). With FLAME masses fed in, ~half the pool
    legitimately re-tiers (the documented M_1 correction) — that is NOT a harness
    bug, it is the committed parquet being stale w.r.t. current code.
  * The raw producer chunks (``data/raw_chunks/main_RA*.parquet``) do NOT carry
    the NSS ``flags`` column (F#33 was added 2026-05-31, after they were made),
    so F#33 no-ops on them. ``flags`` exists offline only inside the committed
    v2 parquet itself.
"""
from __future__ import annotations
import os

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

HERE = Path(__file__).resolve().parent
ROOT = Path(os.path.expanduser("~/claude_projects/gaia-recovered-2026-05-27"))
COMMITTED_V2 = ROOT / "data" / "derived" / "main_hunt_derived_v2.parquet"

for p in (str(HERE), str(HERE.parents[1] / "streaming" / "v2_corrected")):
    if p not in sys.path:
        sys.path.insert(0, p)

import adapter as A          # noqa: E402
import rehunt as RH          # noqa: E402
import diff as D             # noqa: E402
import consumer_v2 as c2     # noqa: E402


# A profile that mirrors the committed parquet's input schema but forces the
# M_1 = 1.5 path the baseline was generated with (no FLAME leak from M1_msun).
_PROFILE_BASELINE = A.Profile(
    name="dr3_derived_fixedM1",
    mapping={**A.DR3_DERIVED.mapping,
             "mass_flame": ["__absent__"],
             "mass_flame_spec": ["__absent__"]},
)


def _load_committed() -> pd.DataFrame:
    import polars as pl
    return pl.read_parquet(COMMITTED_V2).to_pandas()


# ---------------------------------------------------------------------------
# 1) Closed-loop regression — the headline dry-run
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not COMMITTED_V2.exists(), reason="committed v2 parquet absent")
def test_reproduces_committed_roster_exactly():
    """Feed the committed v2 inputs through the harness (M_1=1.5 fixed path) and
    require an EXACT reproduction of the committed tier_v2 + M2 columns."""
    df, adapted = A.load_nss_table(COMMITTED_V2, profile=_PROFILE_BASELINE)
    out = RH.run_cascade(adapted, m1_prior=1.5).set_index("source_id")
    base = _load_committed().set_index("source_id")
    common = base.index.intersection(out.index)
    assert len(common) == len(base) == len(out), "row-count drift"

    tier_mismatch = int(
        (base.loc[common, "tier_v2"].values != out.loc[common, "tier_v2"].values).sum()
    )
    assert tier_mismatch == 0, f"{tier_mismatch} tier mismatches vs committed roster"

    dM2 = (base.loc[common, "M2_msun_v2"] - out.loc[common, "M2_msun_v2"]).abs()
    assert np.nanmax(dM2) < 1e-9, f"M2 drift max={np.nanmax(dM2):.3e}"


@pytest.mark.skipif(not COMMITTED_V2.exists(), reason="committed v2 parquet absent")
def test_diff_against_committed_is_clean_via_self_loop():
    """diff.py on (committed baseline vs harness self-loop) must report no tier
    movement (NEW/PROMOTED/DEMOTED/VANISHED all empty)."""
    df, adapted = A.load_nss_table(COMMITTED_V2, profile=_PROFILE_BASELINE)
    out = RH.run_cascade(adapted, m1_prior=1.5)
    base = _load_committed()[["source_id", "tier_v2", "M2_msun_v2", "P_d"]]
    d = D.diff_rosters(base, out)
    moved = d["change"].isin(["NEW", "PROMOTED", "DEMOTED", "VANISHED"])
    assert moved.sum() == 0, (
        f"{int(moved.sum())} sources moved tiers in self-loop: "
        f"{d.loc[moved, 'change'].value_counts().to_dict()}"
    )


@pytest.mark.skipif(not COMMITTED_V2.exists(), reason="committed v2 parquet absent")
def test_committed_tier1_count_pinned():
    """Pin today's Tier-1 NS+BH roster size (199) so a drift is loud."""
    base = _load_committed()
    n_t1 = int(base["tier_v2"].isin(["Tier-1 NS", "Tier-1 BH"]).sum())
    assert n_t1 == 199, f"committed Tier-1 roster changed: {n_t1} (was 199)"


# ---------------------------------------------------------------------------
# 2) Harness == direct derive_row_v2 (no science fork) — invariant on a slice
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not COMMITTED_V2.exists(), reason="committed v2 parquet absent")
def test_harness_equals_direct_derive_on_slice():
    """run_cascade(adapt(row)) must equal derive_row_v2(adapt(row)) row-by-row."""
    df, adapted = A.load_nss_table(COMMITTED_V2, profile=_PROFILE_BASELINE, limit=500)
    out = RH.run_cascade(adapted, m1_prior=1.5).set_index("source_id")
    for row in adapted:
        direct = c2.derive_row_v2(row, M1_prior=1.5)
        sid = row["source_id"]
        if "error" in direct:
            assert out.at[sid, "tier_v2"] == "ERROR"
            continue
        assert out.at[sid, "tier_v2"] == direct["tier_v2"]
        assert abs(out.at[sid, "M2_msun_v2"] - direct["M2_msun_v2"]) < 1e-12


# ---------------------------------------------------------------------------
# 3) Adapter unit checks
# ---------------------------------------------------------------------------

def test_adapter_computes_a_phot_from_thiele_innes():
    """When no a_phot column is mapped, the adapter derives it from A,B,F,G via
    the production photocentric_a_mas (DR3-raw profile path)."""
    A_, B_, F_, G_ = -0.6366, -0.2300, 0.0960, -0.8180
    expect = c2.photocentric_a_mas(A_, B_, F_, G_)
    row = pd.Series({
        "source_id": 413546904690928000,
        "a_thiele_innes": A_, "b_thiele_innes": B_,
        "f_thiele_innes": F_, "g_thiele_innes": G_,
        "period": 751.3, "eccentricity": 0.07, "parallax": 2.07,
        "nss_solution_type": "AstroSpectroSB1",
    })
    out = A.adapt_row(row, A.DR3_RAW)
    assert out["a_phot_mas"] == pytest.approx(expect, rel=1e-9)
    assert out["source_id"] == 413546904690928000  # exact 18/19-digit int
    assert out["in_sb2"] is False                   # default applied


def test_adapter_first_present_fallback_and_rename():
    """dr3_derived maps period<-[P_d,period]; pick P_d, and logg<-[...,logg]."""
    row = pd.Series({
        "source_id": 1, "a_phot_mas": 1.0, "P_d": 500.0, "e": 0.1,
        "parallax": 2.0, "nss_parallax": 3.0, "logg": 2.5,
        "nss_solution_type": "Orbital",
    })
    out = A.adapt_row(row, A.DR3_DERIVED)
    assert out["period"] == 500.0
    assert out["eccentricity"] == 0.1
    assert out["logg_gspphot"] == 2.5     # mapped from `logg`
    assert out["nss_parallax"] == 3.0


def test_dr4_profile_exists_and_is_runnable_stub():
    """The DR4 profile must exist and at minimum carry source_id + the orbital
    essentials so a DR4 export with DR3-like names runs end-to-end."""
    p = A.get_profile("dr4")
    for k in ("source_id", "period", "eccentricity", "parallax",
              "nss_solution_type"):
        assert p.mapping.get(k), f"dr4 profile missing mapping for {k}"


# ---------------------------------------------------------------------------
# 4) diff.py unit checks — tier ladder semantics
# ---------------------------------------------------------------------------

def _frame(rows):
    return pd.DataFrame(rows)


def test_diff_classifies_new_vanished_promoted_demoted():
    base = _frame([
        {"source_id": 1, "tier_v2": "Tier-1 NS", "M2_msun_v2": 1.5, "P_d": 500},
        {"source_id": 2, "tier_v2": "Tier-2 (RV inconclusive — needs follow-up)",
         "M2_msun_v2": 1.3, "P_d": 600},
        {"source_id": 3, "tier_v2": "Tier-1 BH", "M2_msun_v2": 9.0, "P_d": 1200},
        {"source_id": 4, "tier_v2": "Characterized — M-dwarf companion (0.08 ≤ M_2 < 0.5)",
         "M2_msun_v2": 0.3, "P_d": 400},
    ])
    new = _frame([
        # 1 demoted, 2 promoted to Tier-1, 3 vanished (ERROR), 5 new Tier-1
        {"source_id": 1, "tier_v2": "Demoted (failed F#30 K-giant chromatic)",
         "M2_msun_v2": 1.5, "P_d": 500},
        {"source_id": 2, "tier_v2": "Tier-1 NS", "M2_msun_v2": 1.4, "P_d": 600},
        {"source_id": 3, "tier_v2": "ERROR", "M2_msun_v2": None, "P_d": None},
        {"source_id": 4, "tier_v2": "Characterized — M-dwarf companion (0.08 ≤ M_2 < 0.5)",
         "M2_msun_v2": 0.3, "P_d": 400},
        {"source_id": 5, "tier_v2": "Tier-1 NS", "M2_msun_v2": 1.6, "P_d": 700},
    ])
    d = D.diff_rosters(base, new).set_index("source_id")
    assert d.at[1, "change"] == "DEMOTED"
    assert d.at[2, "change"] == "PROMOTED"
    assert d.at[3, "change"] == "VANISHED"
    assert d.at[4, "change"] == "SAME"
    assert d.at[5, "change"] == "NEW"


def test_diff_flags_mass_mover():
    base = _frame([{"source_id": 1, "tier_v2": "Tier-1 NS", "M2_msun_v2": 1.30, "P_d": 500}])
    new = _frame([{"source_id": 1, "tier_v2": "Tier-1 NS", "M2_msun_v2": 1.50, "P_d": 500}])
    d = D.diff_rosters(base, new, mass_thresh=0.05).set_index("source_id")
    assert d.at[1, "change"] == "MASS_MOVER"
    assert d.at[1, "dM2"] == pytest.approx(0.20)


def test_diff_tier_rank_substring_fallback():
    # Unknown exact label but recognizable prefix still ranks as Tier-1.
    assert D.tier_rank("Tier-1 NS (DR4 refit)") == 90
    assert D.tier_rank("Tier-1 BH something") == 100
    assert D.tier_rank("Demoted (new reason)") == 10
    assert D.tier_rank(None) == -1


# ---------------------------------------------------------------------------
# Script entry point — one-shot offline dry-run summary
# ---------------------------------------------------------------------------

def _dry_run():
    if not COMMITTED_V2.exists():
        print("committed v2 parquet absent; cannot dry-run")
        return
    print("=== DR3 dry-run (self-loop on committed v2 inputs, M_1=1.5 fixed) ===")
    df, adapted = A.load_nss_table(COMMITTED_V2, profile=_PROFILE_BASELINE)
    out = RH.run_cascade(adapted, m1_prior=1.5)
    base = _load_committed()[["source_id", "tier_v2", "M2_msun_v2", "P_d"]]
    d = D.diff_rosters(base, out)
    print(D.render_report(d, "committed main_hunt_derived_v2",
                          "rehunt self-loop (M1=1.5)"))


if __name__ == "__main__":
    _dry_run()
